// <auto-generated />
using System;
using BuildingRESTfulAPIAspNetCore3.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingRESTfulAPIAspNetCore3.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingRESTfulAPIAspNetCore3.Domain.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MainCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Guid");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateTime(1650, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Berry",
                            Guid = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            LastName = "Griffin Beak Eldritch",
                            MainCategory = "Ships"
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateTime(1668, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nancy",
                            Guid = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            LastName = "Swashbuckler Rye",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateTime(1701, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eli",
                            Guid = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            LastName = "Ivory Bones Sweet",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = 4L,
                            BirthDate = new DateTime(1702, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arnold",
                            Guid = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            LastName = "The Unseen Stafford",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = 5L,
                            BirthDate = new DateTime(1690, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Seabury",
                            Guid = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            LastName = "Toxic Reyson",
                            MainCategory = "Maps"
                        },
                        new
                        {
                            Id = 6L,
                            BirthDate = new DateTime(1723, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rutherford",
                            Guid = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            LastName = "Fearless Cloven",
                            MainCategory = "General debauchery"
                        },
                        new
                        {
                            Id = 7L,
                            BirthDate = new DateTime(1721, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Atherton",
                            Guid = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            LastName = "Crow Ridley",
                            MainCategory = "Rum"
                        });
                });

            modelBuilder.Entity("BuildingRESTfulAPIAspNetCore3.Domain.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Guid");

                    b.HasIndex("AuthorId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Description = "Commandeering a ship in rough waters isn't easy.  Commandeering it without getting caught is even harder.  In this course you'll learn how to sail away and avoid those pesky musketeers.",
                            Guid = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            Title = "Commandeering a Ship Without Getting Caught"
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 1L,
                            Description = "In this course, the author provides tips to avoid, or, if needed, overthrow pirate mutiny.",
                            Guid = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Title = "Overthrowing Mutiny"
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 2L,
                            Description = "Every good pirate loves rum, but it also has a tendency to get you into trouble.  In this course you'll learn how to avoid that.  This new exclusive edition includes an additional chapter on how to run fast without falling while drunk.",
                            Guid = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Title = "Avoiding Brawls While Drinking as Much Rum as You Desire"
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 3L,
                            Description = "In this course you'll learn how to sing all-time favourite pirate songs without sounding like you actually know the words or how to hold a note.",
                            Guid = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            Title = "Singalong Pirate Hits"
                        });
                });

            modelBuilder.Entity("BuildingRESTfulAPIAspNetCore3.Domain.Entities.Course", b =>
                {
                    b.HasOne("BuildingRESTfulAPIAspNetCore3.Domain.Entities.Author", "Author")
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BuildingRESTfulAPIAspNetCore3.Domain.Entities.Author", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
